require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

RSpec/ExampleLength:
  Exclude:
    - 'spec/recite_spec.rb'

Layout/LineLength:
  Exclude: 
    - 'spec/recite_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/recite_spec.rb'